services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:9200/_cluster/health || exit 1",
        ]
      interval: 30s
      timeout: 30s
      retries: 3

  embedding_model:
    build:
      context: ../embeddingModel
      dockerfile: Dockerfile
    container_name: embedding_model
    ports:
      - "8000:8000"
    networks:
      - elk
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8001:8001"
    depends_on:
      elasticsearch:
        condition: service_healthy
      embedding_model:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - EMBEDDING_MODEL_URL=http://embedding_model:8000
    networks:
      - elk
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://api:8001/health >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  elk:
    driver: bridge

volumes:
  esdata:
    driver: local
